# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh:
        patterns:
        - '*'

  - package-ecosystem: "docker"
    directory: "/jupyter"
    schedule:
      interval: "weekly"
    groups:
      jupyter-docker:
        patterns:
        - '*'

# Airflow - Base
  - package-ecosystem: "pip"
    directory: "/airflow/base"
    schedule:
      interval: "weekly"
    groups:
      airflow-pip:
        patterns:
        - '*'
  - package-ecosystem: "docker"
    directory: "/airflow/base"
    schedule:
      interval: "weekly"
    groups:
      airflow-docker:
        patterns:
        - '*'

# Airflow - Papermill
  - package-ecosystem: "pip"
    directory: "/airflow/papermill"
    schedule:
      interval: "weekly"
    groups:
      papermill-pip:
        patterns:
        - '*'
  - package-ecosystem: "docker"
    directory: "/airflow/papermill"
    schedule:
      interval: "weekly"
    groups:
      papermill-docker:
        patterns:
        - '*'
