# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/jupyterhub"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/jupyterhub/jkbl"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/airflow"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/knada-gke/airflow"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/knada-gke/jupyterhub"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/knada-gke/airflow"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/jupyterhub"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/jupyterhub/jkbl"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/airflow"
    schedule:
      interval: "weekly"
