version: 2
updates:
- package-ecosystem: docker
  directory: "/jupyterlab"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/jupyterhub"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
