name: "Airflow: Papermill"

on:
  push:
    branches:
      - main
    paths:
      - airflow/papermill/Dockerfile
      - airflow/papermill/requirements.txt
      - .github/workflows/airflow_papermill.yaml
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

env:
  IMAGE: airflow-papermill

jobs:
  build:
    name: Build Airflow papermill image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/193123067890/locations/global/workloadIdentityPools/ci-knada-images/providers/ci-knada-images
          service_account: ci-knada-images@knada-gcp.iam.gserviceaccount.com
      - uses: docker/login-action@v2
        with:
          registry: europe-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependency for compare_tags.py script
        run: pip install backoff==2.2.1
      - name: Check if apache/airflow has updated
        run: |
          knada=$(gcloud artifacts docker images list europe-west1-docker.pkg.dev/knada-gcp/knada/${{ env.IMAGE }} --include-tags --sort-by=~Update_Time --limit=1 --format=json)

          compare_images() {
            out=0
            python3 compare_tags.py airflow "$knada" "2.5.1-python3.10" || out=$?
            if [ $out -eq 100 ]
            then
                echo "OUTDATED=true" >> $GITHUB_ENV
                return 0
            elif [ $out == 0 ]
            then
                return 0
            else
                return $out
            fi
          }

          compare_images
      - uses: docker/setup-buildx-action@v2
      - if: env.OUTDATED == 'true' || contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name)
        run: echo "TAG=$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
      - uses: docker/build-push-action@v4
        if: env.OUTDATED == 'true' || contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name)
        with:
          file: airflow/papermill/Dockerfile
          push: true
          tags: europe-west1-docker.pkg.dev/knada-gcp/knada/${{ env.IMAGE }}:${{ env.TAG }},ghcr.io/${{ github.repository }}/${{ env.IMAGE }}:${{ env.TAG }}
