name: "Build Jupyter image"

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/jupyter.yaml
      - jupyter/Dockerfile
  workflow_dispatch:

env:
  IMAGE: europe-west1-docker.pkg.dev/knada-gcp/jupyterhub/knada-jupyterhub

jobs:
  build:
    name: Build standalone Jupyter image for Python
    strategy:
      matrix:
        version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/193123067890/locations/global/workloadIdentityPools/ci-knada-images/providers/ci-knada-images
          service_account: ci-knada-images@knada-gcp.iam.gserviceaccount.com
      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - run: echo "TAG=$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
      - run: docker build -t $IMAGE:$TAG-${{ matrix.version }} -f jupyter/Dockerfile --build-arg python_version=${{ matrix.version }} .
      - run: docker push $IMAGE:$TAG-${{ matrix.version }}
