name: Jupyterhub: Build R image

on:
  push:
    branches:
      - master
    paths:
      - 'jupyterhub/r/**'
      - '.github/workflows/jupyterhub_r_image.yaml'

env:
  IMAGE: ghcr.io/navikt/jupyterlab-r
  JUPYTER_IAC_REPO: https://api.github.com/repos/navikt/knada-jupyterhub/dispatches

jobs:
  build-jupyterhub-image-R:
    name: Build standalone jupyterhub image for R
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "TAG=$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ${IMAGE}:${TAG} -f jupyterhub/r/Dockerfile .
      - run: docker push ${IMAGE}:${TAG}
      - name: Notify navikt/knada-jupyterhub of image tag update
        run: |
          curl -X POST "${JUPYTER_IAC_REPO}" \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.NAV_REPO_ACCESS_TOKEN }} \
          --data '{"event_type": "update-template-image-tag", "client_payload": { "image": "'"${IMAGE}"'", "tag": "'"${TAG}"'" }}'
