name: Update secondary images

on:
  repository_dispatch:
    types:
      - new-base-image
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - env:
          IMAGE: ${{ github.event.client_payload.image }}
          TAG: ${{ github.event.client_payload.tag }}
        run: sed -i "s~FROM.*~FROM $IMAGE:$TAG~" Dockerfile.jkbl
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: "Base image updated to ${{ github.event.client_payload.tag }}"
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git checkout master
          git commit -am "$COMMIT_MSG"
          git push origin master
